site_name: 上海海事大学智能车实验室技术文档
theme:
  name: readthedocs
  language: zh_CN
  logo: img/logo.png

copyright: Copyright &copy; 2025 上海海事大学智能车实验室 </br> 共享遵循 CC-BY-NC-SA 4.0 &emsp; <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="CC BY-NC-SA 4.0" src="https://licensebuttons.net/l/by-nc-sa/4.0/88x31.png"></a>

plugins:
  - search:
      min_search_length: 1
      lang: 
          - zh
          - en
          - ja
markdown_extensions:
  - admonition

nav:
  - Home: index.md
  - "使用指南": 
      - getting_started/getting_started.md
  - Teams使用指南: 
      - Microsoft Teams 注册指南: teams_tutor/teams_register.md
      - 使用Teams创建审批请求: teams_tutor/teams_approval.md